WIP: Compose out addAsGetterMethod()
DataContainerGenerator.addGetterMethods() defers to
AbstractExplicitGenerator.addAsGetterMethod(), which leads to a quagmire
of overrides and special cases, traversing the graph in non-obvious ways
that lead to constructGetter() et al.

Plenty of generators have a no-op addAsGetterMethod(), which is
completely typical manifestation of the composition vs. inheritance
problem.

So DataContainerMethod is a provisional interface that generators use to
declare themselves as providing these methods, removing all the no-op
implementations.

[ERROR] org.opendaylight.yangtools.binding.generator.impl.Mdsal829Test.testRunTimeTypes -- Time elapsed: 0.006 s <<< ERROR!
java.lang.UnsupportedOperationException: Cannot ascertain type
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.TypeReference$FailedLeafref.methodReturnType(TypeReference.java:87)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.createMethodReturnElementType(AbstractTypeObjectGenerator.java:441)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.methodReturnElementType(AbstractTypeObjectGenerator.java:426)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.methodReturnType(AbstractTypeObjectGenerator.java:419)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerMethod.addAsGetterMethod(DataContainerMethod.java:58)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerMethod.addAsGetterMethod(DataContainerMethod.java:39)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerGenerator.addGetterMethods(DataContainerGenerator.java:470)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.ModuleGenerator.createTypeImpl(ModuleGenerator.java:89)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.ModuleGenerator.createTypeImpl(ModuleGenerator.java:35)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerGenerator.createTypeImpl(DataContainerGenerator.java:459)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.Generator.ensureType(Generator.java:141)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.execute(GeneratorReactor.java:237)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.BindingRuntimeTypesFactory.createTypes(BindingRuntimeTypesFactory.java:69)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.Mdsal829Test.testRunTimeTypes(Mdsal829Test.java:31)
        at java.base/java.lang.reflect.Method.invoke(Method.java:565)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.IllegalArgumentException: Failed to find leafref target /mdsal829:bar
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.strictResolvePath(GeneratorReactor.java:335)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.resolveLeafref(GeneratorReactor.java:325)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.resolveLeafref(AbstractTypeObjectGenerator.java:319)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.bindTypeDefinition(AbstractTypeObjectGenerator.java:292)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.bindTypeDefinition(GeneratorReactor.java:419)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.bindTypeDefinition(GeneratorReactor.java:421)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.execute(GeneratorReactor.java:191)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Data tree child (mdsal829)bar not present in module (mdsal829)mdsal829
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.notPresent(SchemaInferenceStack.java:1053)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.lambda$pushData$0(SchemaInferenceStack.java:861)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.pushData(SchemaInferenceStack.java:861)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.pushFirstData(SchemaInferenceStack.java:869)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.pushData(SchemaInferenceStack.java:847)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.enterDataTree(SchemaInferenceStack.java:531)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.enterChild(SchemaInferenceStack.java:743)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.resolveLocationPath(SchemaInferenceStack.java:722)
        at org.opendaylight.yangtools.yang.model.util@16.0.0-SNAPSHOT/org.opendaylight.yangtools.yang.model.util.SchemaInferenceStack.resolvePathExpression(SchemaInferenceStack.java:658)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.strictResolvePath(GeneratorReactor.java:333)
        ... 11 more

JIRA: YANGTOOLS-1910
Change-Id: Ic18d14d06ffbdfa0399e081755e4b59560bfc43f
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>