Add test to build EffectiveModelContext
If is set SupportedFeatures with empty collection than
BuildEffectiveContext will fail on not related issue.

e.g.:
Caused by: org.opendaylight.yangtools.yang.parser.spi.source
.SourceException: Leaf is missing a 'type' statement [at
 /home/peto/Projects/ODL/yangtools/parser/yang-parser-impl
/target/test-classes/ietf-ip/ietf-ip@2018-02-22.yang:222:11]

at org.opendaylight.yangtools.yang.parser.spi.source
.SourceException.throwIfNull(SourceException.java:205)
...

Signed-off-by: Peter Suna <peter.suna@pantheon.tech>
Change-Id: I5797f09c795587c91f10c7f92a6a8c9fd2480213