WIP: Compose out addAsGetterMethod()
DataContainerGenerator.addGetterMethods() defers to
AbstractExplicitGenerator.addAsGetterMethod(), which leads to a quagmire
of overrides and special cases, traversing the graph in non-obvious ways
that lead to constructGetter() et al.

Plenty of generators have a no-op addAsGetterMethod(), which is
completely typical manifestation of the composition vs. inheritance
problem.

So DataContainerMethod is a provisional interface that generators use to
declare themselves as providing these methods, removing all the no-op
implementations.

[ERROR] org.opendaylight.yangtools.binding.generator.impl.Mdsal829Test.testRunTimeTypes -- Time elapsed: 0.006 s <<< ERROR!
java.lang.UnsupportedOperationException: Cannot ascertain type
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.TypeReference$FailedLeafref.methodReturnType(TypeReference.java:87)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.createMethodReturnElementType(AbstractTypeObjectGenerator.java:441)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.methodReturnElementType(AbstractTypeObjectGenerator.java:426)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.AbstractTypeObjectGenerator.methodReturnType(AbstractTypeObjectGenerator.java:419)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerMethod.addAsGetterMethod(DataContainerMethod.java:58)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerMethod.addAsGetterMethod(DataContainerMethod.java:39)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerGenerator.addGetterMethods(DataContainerGenerator.java:470)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.ModuleGenerator.createTypeImpl(ModuleGenerator.java:89)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.ModuleGenerator.createTypeImpl(ModuleGenerator.java:35)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.DataContainerGenerator.createTypeImpl(DataContainerGenerator.java:459)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.Generator.ensureType(Generator.java:141)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.reactor.GeneratorReactor.execute(GeneratorReactor.java:237)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.BindingRuntimeTypesFactory.createTypes(BindingRuntimeTypesFactory.java:69)
        at org.opendaylight.yangtools.binding.generator@16.0.0-SNAPSHOT/org.opendaylight.yangtools.binding.generator.impl.Mdsal829Test.testRunTimeTypes(Mdsal829Test.java:31)
        at java.base/java.lang.reflect.Method.invoke(Method.java:565)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)

JIRA: YANGTOOLS-1910
Change-Id: Ic18d14d06ffbdfa0399e081755e4b59560bfc43f
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>