Bug 4414: Shorthand case statement not working
Original for shorthand-case was not set at all,
therefore definition in grouping causes
IncorrectNestingException: Supplied class is not valid case

Change-Id: I6941eea52a07967824d2653fbfaedebc5f35ddc9
Signed-off-by: Martin Ciglan <mciglan@cisco.com>