Define xtend.version so downstream users get it
odlparent carries and undefined reference to xtend.version, which breaks
downstream users, as they cannot resolve our dependency. Until that
declaration is removed, for a xtend.version definition to be consistent
with what we require.

Change-Id: Iab374c649da4f8d23ce1c901ede23744ac2c2a05
Signed-off-by: Robert Varga <rovarga@cisco.com>