Drop unused YangSyntaxErrorException
Sonar is pointing out two more methods that do not throw
YangSyntaxErrorException: drop that declaration.

Change-Id: I617716322cf3a614c4d8908116b9f12c587a7f83
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>