Update patch set 1
Patch Set 1: Code-Review-1

This is the first error after reboot:

2017-07-28 10:55:32,737 | WARN  | rd-dispatcher-25 | ShardManager                     | 199 - org.opendaylight.controller.sal-distributed-datastore - 1.5.2.SNAPSHOT | Supervisor Strategy caught unexpected exception - resuming
akka.actor.ActorInitializationException: akka://opendaylight-cluster-data/user/shardmanager-operational/member-1-shard-entity-ownership-operational: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:180)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.ActorCell.create(ActorCell.scala:607)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)[173:com.typesafe.akka.actor:2.4.18]
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)[173:com.typesafe.akka.actor:2.4.18]
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)[173:com.typesafe.akka.actor:2.4.18]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)[173:com.typesafe.akka.actor:2.4.18]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[169:org.scala-lang.scala-library:2.11.11.v20170413-090219-8a413ba7cc]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[169:org.scala-lang.scala-library:2.11.11.v20170413-090219-8a413ba7cc]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[169:org.scala-lang.scala-library:2.11.11.v20170413-090219-8a413ba7cc]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[169:org.scala-lang.scala-library:2.11.11.v20170413-090219-8a413ba7cc]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[:1.8.0_131]
        at akka.util.Reflect$.instantiate(Reflect.scala:65)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.Props.newActor(Props.scala:213)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.ActorCell.newActor(ActorCell.scala:562)[173:com.typesafe.akka.actor:2.4.18]
        at akka.actor.ActorCell.create(ActorCell.scala:588)[173:com.typesafe.akka.actor:2.4.18]
        ... 9 more
Caused by: java.lang.NoSuchMethodError: org.opendaylight.yangtools.triemap.TrieMap.create()Lorg/opendaylight/yangtools/triemap/TrieMap;
        at org.opendaylight.controller.cluster.datastore.entityownership.EntityOwnershipStatistics.<init>(EntityOwnershipStatistics.java:34)[199:org.opendaylight.controller.sal-distributed-datastore:1.5.2.SNAPSHOT]
        at org.opendaylight.controller.cluster.datastore.entityownership.EntityOwnershipShard.<init>(EntityOwnershipShard.java:97)[199:org.opendaylight.controller.sal-distributed-datastore:1.5.2.SNAPSHOT]
        ... 18 more

Patch-set: 1
Reviewer: Gerrit User 2046 <2046@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1