YANGTOOLS-890 - Fix XML parser bug
- when model contains list which has the same name as its
  encapsulating parent container it leads to
  IllegalStateException: Attributes can be extracted only
  from START_ELEMENT.
- added condition to fix END_ELEMENT behavior for lists.


Change-Id: I0d6f6ec356e503fcfc941f18d9133ea0c9cebc6c
Signed-off-by: Michal Cmarada <michal.cmarada@pantheon.tech>